data:
  # Вызывается в result_modifier.php компонента (где будет указано).
  on.result.modifier.component.last.modified:
    event: 'on.result.modifier.component'
    # Класс обработчик.
    handler: '\Prokl\BitrixOrdinaryToolsBundle\Services\SymfonyEvents\Handlers\OnResultModifierSections'
    # Метод слушателя. Если не указано, то "action".
    method: 'action'
    # Приоритет. По умолчанию - 0.
    priority: 100

  # Вызывается в component_epilog.php (где будет указано)
  on.component.epilog.last.modified:
    event: 'on.component.epilog'
    # Класс обработчик.
    handler: '\Prokl\BitrixOrdinaryToolsBundle\Services\SymfonyEvents\Handlers\OnComponentEpilogLastModified'
    # Метод слушателя. Если не указано, то "action".
    method: 'action'
    # Приоритет. По умолчанию - 0.
    priority: 100


  # Установка title & description на детальных страницах.
  set.seo.detail.page:
    event: 'on.component.epilog'
    # Класс обработчик.
    handler: '\Prokl\BitrixOrdinaryToolsBundle\Services\SymfonyEvents\Handlers\Seo\OnDetailSetSeoData'
    priority: 200

  # Канонические ссылки в news.detail.
  canonical.detail:
    event: 'on.result.modifier.component.detail'
    # Класс обработчик.
    handler: '\Prokl\BitrixOrdinaryToolsBundle\Services\SymfonyEvents\Handlers\Seo\Canonical'
    priority: 100

  # H1 в news.list.
  h1.sections:
    event: 'on.result.modifier.component'
    # Класс обработчик.
    handler: '\Prokl\BitrixOrdinaryToolsBundle\Services\SymfonyEvents\Handlers\Seo\H1'
    priority: 250

  # H1 в news.detail.
  h1.detal:
    event: 'on.result.modifier.component.detail'
    handler: '\Prokl\BitrixOrdinaryToolsBundle\Services\SymfonyEvents\Handlers\Seo\H1Detail'
    priority: 350

  on.component.epilog.section.last.modified:
    event: 'on.component.epilog.sections'
    # Класс обработчик.
    handler: '\Prokl\BitrixOrdinaryToolsBundle\Services\SymfonyEvents\Handlers\OnComponentEpilogLastModified'
    # Метод слушателя. Если не указано, то "action".
    method: 'action'
    # Приоритет. По умолчанию - 0.
    priority: 100

  # Установка title & description на разводных страницах.
  set.seo.section.page:
    event: 'on.component.epilog.sections'
    # Класс обработчик.
    handler: '\Prokl\BitrixOrdinaryToolsBundle\Services\SymfonyEvents\Handlers\Seo\OnSectionSetSeoData'
    priority: 200
